/**
 * real-data.ts  (was: mock-data.ts — kept same filename to avoid import changes)
 * Loads live LSTM prediction data from /elephant_data.json (served from /public/).
 * Generated by early_warning_pipeline/export_dashboard_data.py
 */

export interface Elephant {
  id: string;
  name: string;
  gridCell: string;
  position: { lat: number; lng: number };
  horizon: number;
  model: string;
  lastUpdated: string;
  status: "safe" | "warning" | "danger";
}

export interface Prediction {
  rank: number;
  gridCell: string;
  confidence: number;
  location: { lat: number; lng: number };
  distanceKm: number;
  reasoning?: string[];
}

export interface Village {
  name: string;
  distanceKm: number;
  population: number;
  atRisk: boolean;
}

export interface AlertEvent {
  id: string;
  timestamp: string;
  type: "movement" | "boundary" | "proximity" | "prediction";
  severity: "low" | "medium" | "high";
  message: string;
  elephantId: string;
}

export interface MovementPoint {
  hour: string;
  distance: number;
}

// ── Static fallback (shown if fetch fails) ───────────────────────────────────
export const elephants: Elephant[] = [];
export const predictionsMap: Record<string, Prediction[]> = {};
export const villagesMap: Record<string, Village[]> = {};
export const alertEvents: AlertEvent[] = [];
export const movementMap: Record<string, MovementPoint[]> = {};

// ── Loader (called once from App or a React context) ─────────────────────────
export interface DashboardData {
  generatedAt: string;
  elephants: Elephant[];
  predictionsMap: Record<string, Prediction[]>;
  villagesMap: Record<string, Village[]>;
  alertEvents: AlertEvent[];
  movementMap: Record<string, MovementPoint[]>;
  /** [[lat, lon], ...] dead-reckoned historical path per elephant */
  historyMap: Record<string, number[][]>;
}

// API Base URL (can be moved to .env later)
const API_BASE_URL = "http://localhost:8000/api";

export async function loadDashboardData(scenarioId?: number): Promise<DashboardData> {
  try {
    const url = scenarioId 
      ? `${API_BASE_URL}/dashboard-data?scenario_id=${scenarioId}`
      : `${API_BASE_URL}/dashboard-data`;
      
    const res = await fetch(url);
    if (!res.ok) throw new Error(`API failed: ${res.status}`);
    return res.json() as Promise<DashboardData>;
  } catch (err) {
    console.warn("API load failed, falling back to local file", err);
    // Fallback if API is down
    const localFile = scenarioId ? `/scenarios/scenario_${scenarioId}.json` : "/elephant_data.json";
    const res = await fetch(localFile);
    if (!res.ok) throw new Error(`Fallback failed: ${res.status}`);
    return res.json() as Promise<DashboardData>;
  }
}

// Fallback hourly movement (used only if elephant not in movementMap)
export const hourlyMovement: MovementPoint[] = Array.from({ length: 12 }, (_, i) => ({
  hour: `${String(i * 2).padStart(2, "0")}:00`,
  distance: 0,
}));
